### ISSUE TITLE
Game request: Atelier Ryza (G1T images)

### ISSUE THREAD

**Issue by scese250** [marcussacana/Specific-Games#15]
Hi, I know you work mainly on visual novels but my friends said that you can help me :) 

I wonder if you can help me to add support to the newest G1T (image format) to an existing tool, I have plans to translate the game but Gust had updated the G1T format. 

This tool can unpack and repack G1T images, but the author has been inactive for 1 month :/ https://github.com/VitaSmith/gust_tools

This is what I got when I'm trying to unpack a non compatible G1T

![image](https://user-images.githubusercontent.com/12405564/70260284-53e76c80-1766-11ea-958d-40549af97a04.png)

There's examples, with compatible and non compatible G1T. 
[G1T.zip](https://github.com/marcussacana/Specific-Games/files/3928351/G1T.zip)

**Comment by marcussacana** [comment]
looks like have more tools too, you tried this one?
https://github.com/Raytwo/G1Tool

Well, I recommend not having too many expectations on me because I have little experience making texture tools, I will try later but I may not be able to help you with that.

And when I say later maybe you need wait the end of the year, maybe not...

**Comment by scese250** [comment]
Doesn't work, the header is different... I've tried differents tools such like g1tRePack, HyoutaTools, Kuriimu, LINKDATA, no luck. 

No problem, I'll wait. 👍

**Comment by scese250** [comment]
Gust_tool's creator appeared and added support for the new g1t, thanks for you interest!
