### ISSUE TITLE
Game Request: Cartagra ~Affliction of the Soul~

### ISSUE THREAD

**Issue by Greg-xh** [marcussacana/Specific-Games#2]
I saw [the issue](https://github.com/marcussacana/Specific-Games/issues/1), so here I am, lol. 

**Game**: Cartagra
**Publisher**: MangaGamer (ENG) / Innocent Grey (JA)
**Format**: .pac (I think Unity port) / .iga
**VNDB**: https://vndb.org/v515

Thanks.

**Comment by marcussacana** [comment]
too many builds of this game, I think is better you give-me the download link of the version who you wants translate, you can send to my email: ddtank.marcus@gmail.com or just link the vndb release

**Comment by Greg-xh** [comment]
I sent you the link of the version.

**Comment by marcussacana** [comment]
Ok working:
![https://comfy.moe/xdfjfm.png](https://comfy.moe/xdfjfm.png)

but keep in mind he don't works accents because contains a pre-rendered font in the game assets, you will need use the unity engine to create a new pre-rendered font and the tool AssetsExplorer to found the font and replace with a custom font created by you in the unity engine...

Or maybe you can just mod the font in the code using the reflector + reflexil



![https://comfy.moe/jpswob.png](https://comfy.moe/jpswob.png)

Text Only Mod:  (Run as admin to dump the text, you can translate it at main_data\db.lst)
[Cartagra-Mod.rar](https://github.com/marcussacana/Specific-Games/files/1569352/Cartagra-Mod.zip)

**Comment by Greg-xh** [comment]
Thanks. I think I'll google about the font, because I don't know much about Unity... What a pain.
