### ISSUE TITLE
Bypass new M2 crypt from KiriKiriZ engine

### ISSUE THREAD

**Issue by MishaIac** [marcussacana/Specific-Games#30]
Hi, Marcussacana. Saw on vndb that you are working as a programmer on the Spanish translation of [Cafe Stella](https://vndb.org/r88831). I have this question. How did you manage to bypass new M2 crypt? I tried different ways to bypass and it seems to work by dumping all files and then repack them into a new data.xp3 without encryption and using an exe file without encryption. However, to pack the translation, I need to repack all archives, but I want to make just a patch with a small size. If you somehow managed to bypass the protection without repackaging all the archives, is it possible to get the tools to do this? I would be grateful to you. I want to translate this VN into my native language.

**Comment by marcussacana** [comment]
I've determined that M2 has been exploiting the modding community and trying to come up with countermeasures for the tools as we publish, so I've decided not to make the tools completely public as long as they remain compatible with their latest releases.
However, the groups that I can determine are reliable in passing on the tools for translations, I'll help it, however, not immediately, due to some circumstances, if you want access to the tools right away, it's best to ask the Spanish translation group directly.

My discord is: Marcus André#0956

**Comment by MishaIac** [comment]
I see. But I would like to clarify, do the tools that are used in the Spanish translation make an encrypted patch.xp3, or is something else used to bypass the protection? I'm just trying to write a tool myself right now, but I don't know what's the best way to spend my time. I checked and made sure that Cafe Stella uses the patch system, but the rest of VNs on this engine version have the patch system disabled, so the engine won't accept patch.xp3 at all. After all, it is best to make a universal tool.

**Comment by marcussacana** [comment]
continue the discussion on discord
